package models

// Ticket represents the enriched support event generated by the AI.
type Ticket struct {
	Title    string `json:"title"`
	Body     string `json:"body"`
	Priority string `json:"priority"`
	Action   string `json:"action"`
}
